# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  # build is a required step
  build:
    # build in either docker or our own machine; docker is faster
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      # get code from github for build
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        

  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "11:c0:e1:31:ec:fd:77:8c:72:cc:59:cc:0e:7e:b4:0a"      
      - run:
          command: |
            echo deploy is running!
            ssh -oStrictHostKeyChecking=no ec2-user@18.217.185.213 << EOF
              rm -rf BeaganTest
              git clone https://github.com/ct-john/BeaganTest.git
              cd BeaganTest
              npm install
              npm run build
              pm2 stop npm
              pm2 start npm -- start
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy

